# Generated by Django 3.1 on 2020-08-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='model',
            new_name='mod',
        ),
    ]
