# Generated by Django 3.1 on 2020-08-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200827_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='price',
        ),
    ]
