# Generated by Django 3.1 on 2020-08-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_phone_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='mod',
            new_name='model',
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
